# Generated by Django 5.2.7 on 2025-10-19 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_country_of_origin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='products.product')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
            bases=('products.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text='Выберите услуги, которые будут предложены с этим товаром.', related_name='products_offered_with', to='products.service', verbose_name='Сопутствующие услуги'),
        ),
    ]
