# Generated by Django 5.2.7 on 2025-10-20 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_service_product_related_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='related_services',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
