# Generated by Django 5.2.7 on 2025-10-20 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_related_services_delete_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('product', 'Товар'), ('service', 'Услуга')], db_index=True, default='product', max_length=10, verbose_name='Тип'),
        ),
        migrations.AddField(
            model_name='product',
            name='related_services',
            field=models.ManyToManyField(blank=True, help_text='Выберите услуги, которые будут предложены с этим товаром.', limit_choices_to={'product_type': 'service'}, related_name='products_offered_with', to='products.product', verbose_name='Сопутствующие услуги'),
        ),
    ]
