# Generated by Django 5.2.7 on 2025-10-21 12:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_product_type_product_related_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='payment_and_delivery_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text="будет отображаться во вкладке 'Оплата и доставка' на страницах товаров.", verbose_name="Информация 'Оплата и доставка'"),
        ),
    ]
