# Generated by Django 5.2.7 on 2025-10-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_payment_and_delivery_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_show_main',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Показывать на главной'),
        ),
    ]
