# Generated by Django 5.2.7 on 2025-10-12 17:45

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('products', '0002_productimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_key', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('order_type', models.CharField(choices=[('cart', 'Заявка из корзины'), ('callback', 'Заказ обратного звонка'), ('consultation', 'Запрос консультации'), ('price_request', 'Запрос цены'), ('service_request', 'Заказ услуги')], default='cart', max_length=20, verbose_name='Тип заявки')),
                ('name', models.CharField(max_length=100, verbose_name='Имя / Ф.И.О.')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий / Текст заявки')),
                ('file', models.FileField(blank=True, null=True, upload_to='order_files/%Y/%m/', verbose_name='Прикрепленный файл')),
                ('text', models.CharField(blank=True, max_length=255, null=True, verbose_name='Текст')),
                ('total_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Заполняется только для заявок из корзины', max_digits=12, verbose_name='Общая стоимость')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('marketing_consent', models.BooleanField(default=False, verbose_name='Согласие на рекламу')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('filial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='filial.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Все заявки',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=255, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price_type', models.CharField(choices=[('fixed', 'фикс'), ('from', 'от')], default='fixed', max_length=10, verbose_name='Тип цены')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='checkout.order', verbose_name='Заявка')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product')),
            ],
        ),
    ]
