# Generated by Django 5.2.7 on 2025-10-18 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('cart', 'Заявка из корзины'), ('callback', 'Заказ обратного звонка'), ('consultation', 'Запрос консультации'), ('price_request', 'Запрос цены'), ('service_request', 'Заказ услуги'), ('buy_one_clic', 'Купить в 1 клик')], default='cart', max_length=20, verbose_name='Тип заявки'),
        ),
    ]
