# Generated by Django 5.2.7 on 2025-10-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='item_type',
            field=models.CharField(default='product', max_length=10, verbose_name='Тип позиции'),
        ),
    ]
