# Generated by Django 5.2.7 on 2025-10-20 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitem_item_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция в заявке', 'verbose_name_plural': 'Позиции в заявке'},
        ),
    ]
