# Generated by Django 5.2.7 on 2025-10-06 11:12

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название пункта')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL-ключ (слаг)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/catalog/', verbose_name='Картинка')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Описание')),
                ('order_number', models.PositiveIntegerField(default=100, verbose_name='Порядок')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, verbose_name='Скрыть')),
                ('is_show_main', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('show_footer_left', models.BooleanField(default=False, help_text='Отметьте, чтобы этот пункт появился в подвале (левый столбец) сайта.', verbose_name='Показывать в подвале (левый столбец)')),
                ('show_footer_rigth', models.BooleanField(default=False, help_text='Отметьте, чтобы этот пункт появился в подвале (правый столбец) сайта.', verbose_name='Показывать в подвале (правый столбец)')),
                ('is_show_in_header', models.BooleanField(default=False, help_text='Отметьте, чтобы этот пункт появился в выпадающем меню в шапке сайта.', verbose_name='Показывать в верхнем меню')),
                ('show_descendants_products', models.BooleanField(default=True, help_text='Если отмечено, на этой странице будут отображаться товары из всех вложенных подкатегорий. Снимите галочку, чтобы показывать только товары, напрямую связанные с этой категорией.', verbose_name='Показывать товары из подкатегорий')),
                ('seo_title', models.CharField(blank=True, max_length=255, verbose_name='SEO Заголовок (Title)')),
                ('seo_description', models.TextField(blank=True, verbose_name='SEO Описание (Description)')),
                ('seo_keywords', models.TextField(blank=True, null=True, verbose_name='Ключевые слова (мета)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Меню/Каталог',
                'verbose_name_plural': 'Меню/Каталог',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='MenuCatalogFilialVisibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=True, help_text='Если отмечено, эта категория и все ее подкатегории будут скрыты в указанном филиале.', verbose_name='Скрыть в этом филиале')),
            ],
            options={
                'verbose_name': 'Видимость категории',
                'verbose_name_plural': 'Видимость категории.',
            },
        ),
        migrations.CreateModel(
            name='TypeMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название типа')),
                ('template', models.CharField(max_length=724, verbose_name='Название файла шаблона')),
                ('identifier', models.SlugField(help_text="Короткий ключ для использования (напр., 'catalog', 'product')", max_length=100, unique=True, verbose_name='Идентификатор')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Тип меню',
                'verbose_name_plural': 'Типы меню',
                'ordering': ['id'],
            },
        ),
    ]
