# Generated by Django 5.2.7 on 2025-10-06 11:12

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0001_initial'),
        ('menu', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatalog',
            name='applicable_filters',
            field=models.ManyToManyField(blank=True, help_text='Выберите, какие группы фильтров будут отображаться для товаров в этой категории.', to='products.filtercategory', verbose_name='Применимые категории фильтров'),
        ),
        migrations.AddField(
            model_name='menucatalog',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menucatalog', verbose_name='Родительский пункт'),
        ),
        migrations.AddField(
            model_name='menucatalogfilialvisibility',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filial_visibility_rules', to='menu.menucatalog', verbose_name='Категория каталога'),
        ),
        migrations.AddField(
            model_name='menucatalogfilialvisibility',
            name='filial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_categories', to='filial.filial', verbose_name='Филиал'),
        ),
        migrations.AddField(
            model_name='menucatalog',
            name='type_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='catalogs', to='menu.typemenu', verbose_name='Тип меню'),
        ),
        migrations.AlterUniqueTogether(
            name='menucatalogfilialvisibility',
            unique_together={('category', 'filial')},
        ),
    ]
