# Generated by Django 5.2.7 on 2025-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucatalog',
            name='hover_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/cataloghover/', verbose_name='Изображение при наведении на главном'),
        ),
    ]
