# Generated by Django 5.2.7 on 2025-10-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_menucatalog_hover_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menucatalog',
            old_name='show_footer_rigth',
            new_name='show_footer_right',
        ),
    ]
