# Generated by Django 5.2.7 on 2025-10-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Например, 'Москва'.", max_length=100, verbose_name='Название')),
                ('name_info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название (падеж для подстановки)')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Область')),
                ('order_number', models.PositiveIntegerField(blank=True, help_text='Чем меньше число, тем выше в списке. Оставьте пустым для сортировки по алфавиту.', null=True, verbose_name='Порядок')),
                ('is_hidden', models.BooleanField(db_index=True, default=False, help_text='Отключите, чтобы скрыть филиал со всего сайта.', verbose_name='Скрыть')),
                ('subdomain', models.CharField(db_index=True, help_text="Например, 'sp' для sp.kzmc.kz", max_length=100, unique=True, verbose_name='Поддомен')),
                ('is_default', models.BooleanField(db_index=True, default=False, help_text='Отметьте для филиала, который будет отображаться на основном домене.', verbose_name='Основной сайт (без поддомена)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('phone_dop', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон (дополнительный)')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=256, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Режим работы')),
                ('full_name_req', models.CharField(blank=True, max_length=256, verbose_name='Полное наименование предприятия')),
                ('short_name_req', models.CharField(blank=True, max_length=256, verbose_name='Краткое наименование предприятия')),
                ('inn_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИНН')),
                ('kpp_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='КПП')),
                ('bin_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИН (КЗ)')),
                ('ikk_1_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИКК 1 (КЗ)')),
                ('ikk_2_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ИКК 2 (КЗ)')),
                ('yr_address_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Юридический адрес')),
                ('fact_address_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фактический адрес')),
                ('phone_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Телефон (реквизиты)')),
                ('email_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Электронная почта (реквизиты)')),
                ('okved_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКВЭД')),
                ('okpo_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКПО')),
                ('okato_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКАТО')),
                ('okfs_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКФС')),
                ('okopf_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКОПФ')),
                ('bank_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Банк')),
                ('bik_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='БИК')),
                ('chet_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='Расчетный счет')),
                ('korr_chet_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='Коректирующий счет')),
                ('nalog_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Постановка в налоговый учет')),
                ('reg_req', models.CharField(blank=True, max_length=256, null=True, verbose_name='Госрегистрация')),
                ('ogrn_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОГРН')),
                ('oktmo_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='ОКТМО')),
                ('director_req', models.CharField(blank=True, max_length=100, null=True, verbose_name='Директор (на основании устава)')),
                ('requisites_file', models.FileField(blank=True, null=True, upload_to='filials/requisites/', verbose_name='Файл с реквизитами')),
                ('map_code', models.TextField(blank=True, help_text='HTML-код для вставки карты, например, с Яндекс.Карт.', verbose_name='Код карты проезда')),
                ('seo_text_head', models.TextField(blank=True, help_text='Дополнительные скрипты или мета-теги, которые будут добавлены в <head>.', verbose_name='Блок в <head> для филиала')),
                ('seo_text_body', models.TextField(blank=True, help_text='Дополнительные скрипты, которые будут добавлены в конце <body>.', verbose_name='Блок в <body> для филиала')),
                ('is_base', models.BooleanField(blank=True, default=False, verbose_name='Популярные города')),
                ('robots_txt_override', models.TextField(blank=True, help_text='Если заполнено, будет использоваться этот robots.txt для данного филиала. Иначе будет использоваться шаблон по умолчанию. Используйте {host} и {main_domain}.', verbose_name='Переопределение Robots.txt')),
                ('sitemap_filename', models.CharField(blank=True, help_text="Например, 'sitemap_ekb.xml'. Если оставить пустым, будет использовано 'sitemap.xml'.", max_length=100, verbose_name='Имя файла Sitemap')),
                ('parent', models.ForeignKey(blank=True, help_text='Выберите главный филиал.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='filial.filial', verbose_name='Основной (родительский) филиал')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы (Города)',
            },
        ),
    ]
