# Generated by Django 5.2.7 on 2025-10-21 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filial', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filial',
            old_name='requisites_file',
            new_name='req_file',
        ),
    ]
