# Generated by Django 5.2.7 on 2025-10-24 09:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filial', '0002_rename_requisites_file_filial_req_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="Уникальный идентификатор для использования в шаблонах, напр., 'homepage-cover-text'", max_length=100, verbose_name='Системный ключ (slug)')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='HTML текст')),
                ('comment', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Комментарий для администратора')),
                ('filial', models.ForeignKey(blank=True, help_text='Оставьте пустым, если этот текст является глобальным по умолчанию.', null=True, on_delete=django.db.models.deletion.CASCADE, to='filial.filial', verbose_name='Филиал')),
            ],
            options={
                'verbose_name': 'Статический текст',
                'verbose_name_plural': 'Статические тексты',
                'ordering': ['slug', 'filial__name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('filial__isnull', True)), fields=('slug',), name='unique_global_static_text_slug'), models.UniqueConstraint(fields=('slug', 'filial'), name='unique_filial_static_text_slug')],
            },
        ),
    ]
