# Generated by Django 5.2.7 on 2025-10-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articlecategory_alter_articles_order_number_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['category', 'is_hidden', '-date'], name='idx_articles_cat_hidden_date'),
        ),
    ]
