# Generated by Django 5.2.7 on 2025-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_articles_idx_articles_cat_hidden_date'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='articles',
            index=models.Index(fields=['is_hidden', 'is_show_main', '-date'], name='idx_articles_main_page'),
        ),
    ]
