# Generated by Django 5.2.7 on 2025-10-06 12:32

import apps.gallery.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Для вашего удобства, для поиска', max_length=200, verbose_name='Название (необязательно)')),
                ('image', models.ImageField(upload_to=apps.gallery.models.gallery_image_upload_path, verbose_name='Изображение')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
            options={
                'verbose_name': 'Импорт изображения',
                'verbose_name_plural': 'Импорт изображений',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
