# Generated by Django 5.2.7 on 2025-10-06 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название компании')),
                ('site_name', models.CharField(max_length=256, verbose_name='Название сайта')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Логотип')),
                ('type_company', models.CharField(blank=True, max_length=256, null=True, verbose_name='Тип компании')),
                ('count_staff', models.CharField(blank=True, max_length=256, null=True, verbose_name='Количество сотрудников')),
                ('start_year', models.CharField(blank=True, max_length=50, null=True, verbose_name='Год основания')),
                ('main_phone', models.CharField(blank=True, max_length=50, verbose_name='Основной телефон')),
                ('main_email', models.EmailField(blank=True, max_length=254, verbose_name='Основной email')),
                ('main_address', models.CharField(blank=True, max_length=255, verbose_name='Основной адрес')),
                ('main_map_code', models.TextField(blank=True, help_text='HTML-код для вставки карты, например, с Яндекс.Карт.', verbose_name='Основной код карты')),
                ('main_working_hours', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Основной режим работы')),
                ('text_head', models.TextField(blank=True, null=True, verbose_name='Блок в head (внизу)')),
                ('text_body', models.TextField(blank=True, null=True, verbose_name='Блок в body (внизу)')),
                ('robots_txt_default', models.TextField(blank=True, help_text='Шаблон по умолчанию. Используйте {host} для подстановки текущего домена (напр., ekb.mtk-novator.ru) и {main_domain} для основного домена (напр., mtk-novator.ru).', verbose_name='Robots.txt по умолчанию')),
            ],
            options={
                'verbose_name': 'Настройка проекта',
                'verbose_name_plural': 'Настройки проекта',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('icon', models.FileField(upload_to='icons/', verbose_name='Иконка (SVG)')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Активен')),
                ('project_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advantages', to='project_settings.projectsettings')),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
                'ordering': ['order_number'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('icon_name', models.CharField(blank=True, default='', max_length=128, verbose_name='Название значка')),
                ('name', models.CharField(max_length=724, verbose_name='URL ссылки')),
                ('icon_image', models.ImageField(blank=True, null=True, upload_to='uploads/images', verbose_name='Картинка')),
                ('is_hidden', models.BooleanField(blank=True, default=False, verbose_name='Скрыть')),
                ('project_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='project_settings.projectsettings')),
            ],
            options={
                'verbose_name': 'Социальная ссылка',
                'verbose_name_plural': 'Социальные ссылки',
                'ordering': ['order_number', 'name'],
            },
        ),
    ]
