# Generated by Django 5.2.7 on 2025-10-21 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsettings',
            name='marketing_agreement_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл с условиями рекламной рассылки (если требуется).', null=True, upload_to='docs/', verbose_name="Файл 'Согласие на получение материалов'"),
        ),
        migrations.AddField(
            model_name='projectsettings',
            name='privacy_policy_file',
            field=models.FileField(blank=True, help_text='Загрузите PDF файл с политикой конфиденциальности.', null=True, upload_to='docs/', verbose_name="Файл 'Политика обработки персональных данных'"),
        ),
    ]
